#!/usr/bin/env python3
"""Generate hooks/status/fixtures.gen.ts from hooks/status/fixtures/.

A `claude plugin test` file cannot read files, so the status mod's tests
read the fixture directories through this generated module. Each fixture
directory becomes one entry: its files keyed by absolute in-memory path
(the fixture directory is `/`), the session's working directory, and the
rows its `expected.json` states. The module also lists the plugin's skill
names, one per `skills/*/SKILL.md`, which the band's label map is held to
(M195).

    python3 hooks/status/gen_fixtures.py          # rewrite the module
    python3 hooks/status/gen_fixtures.py --check  # exit 1 when stale

`scripts/tests/test_status_fixtures.py` fails when the committed module
differs from `render()`.
"""

import json
import os
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
FIXTURES = HERE / "fixtures"
SKILLS = HERE.parents[1] / "skills"
MODULE = HERE / "fixtures.gen.ts"

HEADER = (
    "// Generated by hooks/status/gen_fixtures.py from hooks/status/fixtures/\n"
    "// and the skill directories under skills/.\n"
    "// Do not edit: change those directories and run the generator.\n"
    "import type { Fixture } from './reader'\n\n"
)


def load(case_dir):
    """(cwd, files, rows) for one fixture directory."""
    expected = json.loads((case_dir / "expected.json").read_text(encoding="utf-8"))
    files = {}
    for path in sorted(case_dir.rglob("*")):
        if not path.is_file() or path.name == "expected.json":
            continue
        rel = path.relative_to(case_dir).as_posix()
        files["/" + rel] = path.read_text(encoding="utf-8")
    cwd = "/" + expected["cwd"] if expected["cwd"] else "/"
    return cwd, files, expected["rows"]


def cases():
    return sorted(p for p in FIXTURES.iterdir() if p.is_dir())


def skills():
    """The plugin's skill names: each directory under skills/ with a SKILL.md."""
    return sorted(p.parent.name for p in SKILLS.glob("*/SKILL.md"))


def render():
    out = [HEADER, "export const SKILLS: string[] = [\n"]
    for name in skills():
        out.append(f"  {json.dumps(name)},\n")
    out.append("]\n\n")
    out.append("export const FIXTURES: Record<string, Fixture> = {\n")
    for case_dir in cases():
        cwd, files, rows = load(case_dir)
        out.append(f"  {json.dumps(case_dir.name)}: {{\n")
        out.append(f"    cwd: {json.dumps(cwd)},\n")
        out.append("    files: {\n")
        for key, text in files.items():
            out.append(f"      {json.dumps(key)}: {json.dumps(text, ensure_ascii=False)},\n")
        out.append("    },\n")
        out.append("    rows: [\n")
        for row in rows:
            out.append(f"      {json.dumps(row, ensure_ascii=False)},\n")
        out.append("    ],\n")
        out.append("  },\n")
    out.append("}\n")
    return "".join(out)


def main(argv):
    text = render()
    if "--check" in argv:
        current = MODULE.read_text(encoding="utf-8") if MODULE.exists() else ""
        if current != text:
            print(f"{os.path.relpath(MODULE)} is stale: run python3 hooks/status/gen_fixtures.py")
            return 1
        return 0
    MODULE.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
